### ISSUE TITLE
error: Import Error occured in Module imports due to: No module named 'alive_progress'

### ISSUE THREAD

**Issue by piyushimself** [RevoltSecurities/Dnsbruter#1]
When running the dnsbruter, getting the msg,

dnsbruter -h
[WRN]: Import Error occured in Module imports due to: No module named 'alive_progress'
[INFO]: If you are encountering this issue more than a time please report the issues in Dnsbruter Github page..

**Comment by RevoltSecurities** [comment]
Hi @piyushimself ,
Thank you for creating issue , To resolve the issue please use this command:

```bash
pip install alive_progress
```

Kind regards,
@RevoltSecurities

**Comment by piyushimself** [comment]
Tried and successfully installed it. But issue is not resolved.

**Comment by RevoltSecurities** [comment]
Hello @piyushimself ,

Hi please install the command as a root user

Kind regards,
@RevoltSecurities

**Comment by piyushimself** [comment]
Triad with root user only.
<img width="951" alt="Screenshot_1" src="https://github.com/RevoltSecurities/Dnsbruter/assets/11846992/0dfb048c-9e83-4a3c-8cd1-f9ddfd7ad121">

**Comment by RevoltSecurities** [comment]
Hi @piyushimself ,

Looks like some packages are missing so I request you to please you the command to install the Dnsbruter with this command as a root user:
```bash
pip uninstall dnsbruter 

pip install git+https://github.com/RevoltSecurities/Dnsbruter 
```
if you are facing this issue please reply, we are available to resolve your issues.
Kind regards,
@RevoltSecurities

**Comment by piyushimself** [comment]
Thanks, it worked.

**Comment by RevoltSecurities** [comment]
Hi @piyushimself ,
If your issue is resolved then we request you to close this issue as completed.

Kind regards,
@RevoltSecurities
